### PR TITLE
Type 3 Level 1 Problem 2 Happy Number

### PR DESCRIPTION
**Pull request by hee-soh-ka**

### CODE REVIEW

**Comment by xLAVAxMASTERx** [comment]
Issues:
Happy Number is problem 2 not problem one

**Comment by xLAVAxMASTERx** [comment]
Change file name and make a new commit

**Comment by hee-soh-ka** [comment]
@xLAVAxMASTERx done

**Comment by 0xd1r** [comment]
Looks good now. Merging!

**Pull request merged**
