### PR TITLE
Solves issue #308

### PR DESCRIPTION
**Pull request by GeRmAnImAl**
Implemented solution in Java for Type 3, Level 1, Problem 3.

### CODE REVIEW

**Review by SuchirRP — CHANGES_REQUESTED** [review]
image
**Issues:** Unwanted extra files are a part of the pr
**Recommends:** Delete all extra files other than the problem solution, commit and push again at which point pr will be considered again

**Comment by GeRmAnImAl** [comment]
@SuchirRP the unwanted files have been removed and a new commit was made.

**Review by xLAVAxMASTERx — CHANGES_REQUESTED** [review]
Issues:
Checked your new commit but file extension for java is not given in file name , fix the issue and commit again Thank You

**Comment by GeRmAnImAl** [comment]
@xLAVAxMASTERx file extension has been added.

**Review by SuchirRP — CHANGES_REQUESTED** [review]
**Issues:**The function is not being called and not user input is being taken
**Recommends:** Fix issues commit and push again

**Pull request closed without merging**
