### PR TITLE
Added tictactoe

### PR DESCRIPTION
**Pull request by SuchirRP**
storage location Type_2/Tic-Tac/SuchirRP_tic_tac/tictactoe.py

### CODE REVIEW

**Comment by xLAVAxMASTERx** [comment]
game works fine , incase of out of range the program stops rather give user a message.

**Comment by 0xd1r** [comment]
**Issues:** 
1. When user inputs location that is out of bound, the program exits with `IndexError: list index out of range`. Should be corrected to include a user readable error message, and how to correct the inputs.
2. When user inputs coordinates with a line break, the program exits with `ValueError: not enough values to unpack (expected 2, got 1)`. Should be corrected to accept such inputs.

Reply with a confirmation post changes and we will look into your program again, pre the merge.

**Comment by xLAVAxMASTERx** [comment]
Note the issues mentioned in the previous comment
Closing pull request make a new pull request after fixing the bugs.

**Comment by SuchirRP** [comment]
Fixed the mentioned bugs, will open new pr

**Pull request closed without merging**
